stages:
  build-features:
    cmd: python src/features/build_features.py
    deps:
    - data/raw/test-00000-of-00001.parquet
    - data/raw/train-00000-of-00001.parquet
    - data/raw/validation-00000-of-00001.parquet
    - src/features/build_features.py
    outs:
    - data/processed/
  train-model:
    cmd: python src/models/train_model.py
    deps:
    - data/processed/test.csv
    - data/processed/train.csv
    - data/processed/validate.csv
    - src/models/train_model.py
    outs:
    - models/
